name: Go package
on: workflow_dispatch
jobs:    
  ansibleplaybook:
   runs-on: ubuntu-latest
   steps:
      - name: run ansible playbook
        uses: dawidd6/action-ansible-playbook@v1
      - name: playbook  
        run: ansible-playbook demo.yaml
