name: Go package
on: workflow_dispatch
jobs:    
  ansibleplaybook:
   runs-on: ubuntu-latest
   steps:
   - name: Run playbook
     uses: dawidd6/action-ansible-playbook@v2
     with:
    # Required, playbook filepath
      playbook: demo.yaml
      # Optional, directory where playbooks live
      directory: ./
   - name: run ansible playbook
     run: ansible-playbook demo.yaml
